; Local development
expose_php = Off
zend.assertions = -1
zend.detect_unicode = 0

memory_limit = 512M

opcache.memory_consumption = 256
opcache.interned_strings_buffer = 20
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.file_cache = /tmp/php-opcache
opcache.file_cache_only = 0

realpath_cache_size = 16M
realpath_cache_ttl = 3600

max_execution_time = 300
upload_max_filesize = 128M
post_max_size = 128M

