services:
  OptiwebProductEnquiry\Core\Content\ProductEnquiry\ProductEnquiryDefinition:
    tags:
      - { name: shopware.entity.definition }

  OptiwebProductEnquiry\Content\Cms\DataResolver\Element\ProductEnquiryCmsElementResolver:
    arguments:
      $salutationRepository: '@salutation.repository'
      $productRepository: '@product.repository'
    tags:
      - { name: shopware.cms.data_resolver }

  OptiwebProductEnquiry\Controller\ProductEnquiryController:
    public: true
    autoconfigure: true
    autowire: true
    arguments:
      $mailService: '@Shopware\Core\Content\Mail\Service\MailService'
    tags:
      - { name: controller.service_arguments }
