services:
    OptiwebProductEnquiry\Content\Cms\DataResolver\Element\ProductEnquiryCmsElementResolver:
        tags:
            - { name: shopware.cms.data_resolver }
        arguments:
            $salutationRepository: '@salutation.repository'
            $productRepository: '@product.repository'

    OptiwebProductEnquiry\Controller\ProductEnquiryController:
        public: true
        arguments:
            $systemConfigService: '@Shopware\Core\System\SystemConfig\SystemConfigService'
            $mediaService: '@Shopware\Core\Content\Media\MediaService'
            $mailService: '@Shopware\Core\Content\Mail\Service\MailService'
            $productRepository: '@product.repository'
            $mailTemplateRepository: '@mail_template.repository'
            $mailTemplateTypeRepository: '@mail_template_type.repository'
            $logEntryRepository: '@log_entry.repository'
            $cmsSlotRepository: '@cms_slot.repository'
            $validator: '@validator'
        calls:
            - method: setContainer
              arguments: ['@service_container']
        tags:
            - { name: controller.service_arguments }
