[program:shopware-async]
command=/usr/local/bin/php /var/www/html/bin/console messenger:consume async --memory-limit=4096M
process_name=%(program_name)s_%(process_num)02d
numprocs=2
autostart=true
autorestart=true
user=application
stdout_logfile=/var/log/shopware-async.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/shopware-async-error.log
stderr_logfile_maxbytes=10MB

[program:shopware-low-priority]
command=/usr/local/bin/php /var/www/html/bin/console messenger:consume low_priority --memory-limit=4096M
process_name=%(program_name)s
numprocs=1
autostart=true
autorestart=true
user=application
stdout_logfile=/var/log/shopware-low-priority.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/shopware-low-priority-error.log
stderr_logfile_maxbytes=10MB

[program:shopware-scheduler]
command=/bin/bash -c 'while true; do /usr/local/bin/php /var/www/html/bin/console scheduled-task:run; sleep 60; done'
process_name=%(program_name)s
autostart=true
autorestart=true
user=application
stdout_logfile=/var/log/shopware-scheduler.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/shopware-scheduler-error.log
stderr_logfile_maxbytes=10MB
